title: Peng's Homepage
author: Artist Working with Data
description: ""

plugins:
  - jekyll-redirect-from
  - jekyll-feed

theme: minima

header_pages:
  - contact/github.md
  - contact/instagram.md
  
