title: PENG's HOMEPAGE
author: Artist Working with Data
description: ""

plugins:
  - jekyll-redirect-from

# theme: minima
remote_theme: lilianweng/lil-log

header_pages:
  - contact/github.md
  - contact/instagram.md
  
